bf2fc6cc711aee1a0c2a/cos-ui

- cypress/integration/create-connector.spec.ts
- package-lock.json
- package.json
- src/apis/api.ts
- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.tsx
https://issues.redhat.com/browse/MGDCTRS-469
> MGDCTRS-469: Get rid of the extra verify config button

- src/app/components/ConnectorsToolbar/ConnectorsToolbar.tsx
- src/app/components/CreateConnectorWizard/CreateConnectorWizard.css
- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.css
- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.tsx
- src/app/components/StepBodyLayout/StepBodyLayout.tsx
- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
- src/app/pages/CreateConnectorPage/StepBasic.tsx
- src/app/pages/CreateConnectorPage/StepClusters.tsx
- src/app/pages/CreateConnectorPage/StepConnectorTypes.tsx
- src/app/pages/CreateConnectorPage/StepErrorHandling.tsx
- src/app/pages/CreateConnectorPage/StepKafkas.tsx
- src/app/pages/CreateConnectorPage/StepReview.tsx
https://issues.redhat.com/browse/MGDCTRS-218
> MGDCTRS-218:Improve connector specific form Layout, fonts, spacing etc

- src/CosRoutes.tsx
- src/apis/api.ts
- src/app/components/ConnectorsTable/ConnectorsTable.tsx
- src/app/pages/ConnectorDetailsPage/CommonStep.tsx
https://issues.redhat.com/browse/MGDCTRS-256
> MGDCTRS-256: Add the API error handling on the last/Review step

- src/app/components/ConnectorDrawer/ConnectorDrawer.tsx
https://issues.redhat.com/browse/MGDCTRS-504
> MGDCTRS-504: fix: add connector id to the details drawer.

- src/CosRoutes.tsx
- src/app/components/CreateConnectorWizard/CreateConnectorWizard.css
- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.css
- src/app/machines/StepConfiguratorLoader.machine.ts
- src/app/machines/StepReview.machine.ts
- src/app/pages/ConnectorDetailsPage/ConfigurationPage.tsx
- src/app/pages/ConnectorDetailsPage/ConnectorDetailsPage.tsx
- src/utils/shared.ts
Jira issue https://issues.redhat.com/browse/MGDCTRS-512
> MGDCTRS-512: UI component for DBZ connector edit flow

- .github/workflows/main.yml
This will help ensure the main branch builds.  This change also adds
building storybook as a check, and also builds it on the main branch.
@indraraj @uidoyen does this sound alright for you?
> chore: Run build for PRs, fixes #410

- src/app/components/ConnectorsToolbar/ConnectorsToolbar.tsx
With the move to using a paginated response, any filtering and sorting
would need to be done at the API.
> MGDCTRS-486: chore: remove the search widget

- src/app/pages/ConnectorDetailsPage/ErrorHandlerStep.tsx
- src/app/pages/CreateConnectorPage/StepErrorHandling.tsx
Closes the issue 
https://issues.redhat.com/browse/MGDCTRS-729
> MGDCTRS-729: fix: use the default value in error handling step

- locales/en/public.json
- src/app/pages/CreateConnectorPage/StepConnectorTypes.tsx
> MGDCTRS-562:feat:add guidance about what is sink & source

- src/app/components/ConnectorActions/ConnectorActionsMenu.tsx
- src/app/components/ConnectorDrawer/ConnectorDrawer.tsx
- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
https://issues.redhat.com/browse/MGDCTRS-568
> MGDCTRS-568:feat:Add actions menu in the drawer

- src/app/pages/CreateConnectorPage/StepConfigurator.tsx
fixes https://issues.redhat.com/browse/MGDCTRS-838
> MGDCTRS-838: fix: fix duplicate flow for DBZ based connectors

- locales/en/public.json
- src/app/pages/CreateConnectorPage/DuplicateConnectorPage.tsx
- src/app/pages/CreateConnectorPage/StepConfigurator.tsx
https://issues.redhat.com/browse/MGDCTRS-616
As per discussion in the UX call, this feature is implemented just for duplicate connectors.
https://issues.redhat.com/browse/MGDCTRS-567
Synchronizes the title with sub-step label
> MGDCTRS-616, MGDCTRS-567:feat:address UX recommendation

- locales/en/public.json
- src/app/pages/CreateConnectorPage/StepKafkas.tsx
- src/app/pages/CreateConnectorPage/StepNamespace.tsx
Jira: https://issues.redhat.com/browse/MGDCTRS-863
> MGDCTRS-863:feat:Link Create Kafka instance buttons and addon instructions

- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
Jira: https://issues.redhat.com/browse/MGDCTRS-899
> MGDCTRS-899: fix:quick start link on empty state doesn't open drawer

- src/apis/api.ts
Fixes https://issues.redhat.com/browse/MGDCTRS-905
> MGDCTRS-905: chore: passing an empty annotations for eval creation

- src/app/components/ConnectorDrawer/ConnectorDrawer.tsx
- src/app/pages/ConnectorDetailsPage/OverviewPage.tsx
> MGDCTRS-939: chore: Add support email to the failed connectors details.

- src/app/components/ConnectorStatus/ConnectorStatus.stories.tsx
Realized that this storybook had not been updated, this change rectifies
that.
> MGDCTRS-787 fix: update statuses storybook

- src/app/components/ConnectorStatus/ConnectorStatus.stories.tsx
- src/app/components/ConnectorStatus/ConnectorStatus.tsx
- src/app/components/ConnectorsTable/ConnectorsTable.tsx
> chore: Add clickable connector state Label

- package-lock.json
- src/app/pages/CreateConnectorPage/StepNamespace.tsx
Fixes: https://issues.redhat.com/browse/MGDCTRS-1000
Screenshot
> MGDCTRS-1000: fix: Fix the transition state for namespace

- src/app/machines/CreateConnectorWizard.machine.ts
https://issues.redhat.com/browse/MGDCTRS-1006
> fix:MGDCTRS-1006:fixes 2nd step is not highlighted upon selection of KI

- src/app/components/ConnectorsToolbar/ConnectorsToolbar.tsx
- src/app/components/CreateServiceAccount/CreateServiceAccount.tsx
- src/app/components/EmptyStateGettingStarted/EmptyStateGettingStarted.tsx
- src/app/components/UncontrolledWizard/UncontrolledWizard.tsx
- src/app/pages/CreateConnectorPage/StepCommon.tsx
- src/app/pages/CreateConnectorPage/StepConnectorTypes.tsx
- src/app/pages/CreateConnectorPage/StepNamespace.tsx
- src/app/pages/CreateConnectorPage/StepReview.tsx
This change adds ouia IDs to elements to help aid usage tracking across
pages in the create connection wizard.
> MGDCTRS-1068 chore: add ouia IDs

- .env
- src/app/pages/CreateConnectorPage/StepConfigurator.tsx
Fixes: https://issues.redhat.com/browse/MGDCTRS-1093
> MGDCTRS-1093: fixes duplicate flow in DBZ 

- src/app/components/ViewJSONFormat/ViewJSONFormat.tsx
The changes updates service account keys.
> MGDCTRS-798:chore:update service account keys

- .env
- locales/en/public.json
- src/app/pages/CreateConnectorPage/StepConnectorTypes.css
- src/app/pages/CreateConnectorPage/StepConnectorTypes.tsx
Card view update based on new design here https://issues.redhat.com/browse/MGDCTRS-1059. 
Connectors(Sink&Source) logos are placeholder. We will change logos after the finalization.
> MGDCTRS-1059:feat:Add custom logo for connectors (sink&Source)

- .storybook/main.js
- .storybook/preview.js
- locales/en/public.json
- src/app/components/ConnectorDrawer/ConnectorDrawer.stories.tsx
- src/app/components/ConnectorDrawer/ConnectorDrawer.tsx
- src/app/components/ConnectorDrawer/DrawerHeader.tsx
- src/app/components/ConnectorInfoTextList/ConnectorInfoTextList.stories.tsx
- src/app/components/ConnectorInfoTextList/ConnectorInfoTextList.tsx
- src/app/components/ConnectorStatus/ConnectorStatus.stories.tsx
- src/app/components/DialogDeleteConnector/DialogDeleteConnector.stories.tsx
- src/app/components/Pagination/Pagination.stories.tsx
- src/app/pages/ConnectorDetailsPage/OverviewTab.tsx
- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
- Added the helper text for the "Duplicate connector instance" button in the drawer
- Fixed Drawer story 
- Refactored ConnectorDrawer and ConnectorInfoTextList Component
Screenshot
> Chore: Fixed broken stories and added more

- package-lock.json
- package.json
This explicitly adds @patternfly/react-charts which is needed by
app-services-ui-components.
> chore: add @patternfly/react-charts dep

- src/apis/api.ts
- src/app/components/ConnectorDrawer/ConnectorDrawer.stories.tsx
- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
Closes https://issues.redhat.com/browse/MGDCTRS-1419
Screenshot
> MGDCTRS-1419: fix: disable clickable connector name for deleted desired_state

- src/app/components/CreateConnectorWizard/CreateConnectorWizard.tsx
This change slightly modifies how configuration sub-steps are created
and adjusts how the goToStep function used by the wizard tree indexes
the flattened step array.
> MGDCTRS-1049 fix: rework config step logic

- cypress/e2e/connectors-instances.cy.ts
- cypress/fixtures/connectorsPolling.json
- src/app/components/ConnectorActions/ConnectorActionsMenu.tsx
- src/app/components/ConnectorDrawer/ConnectorDrawer.stories.tsx
- src/app/components/ConnectorTypeCard/ConnectorTypeCard.stories.tsx
- src/app/components/ConnectorsToolbar/ConnectorsToolbar.stories.tsx
- src/app/components/DialogDeleteConnector/DialogDeleteConnector.stories.tsx
- src/app/components/ViewJSONFormat/ViewJSONFormat.stories.tsx
- src/app/pages/ConnectorDetailsPage/ConnectorDetailsHeader/ConnectorDetailsHeader.tsx
- src/app/pages/ConnectorsPage/ConnectorsPage.stories.tsx
- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
- src/app/pages/CreateConnectorPage/StepConnectorTypes.tsx
Closes https://issues.redhat.com/browse/MGDCTRS-1419 https://issues.redhat.com/browse/MGDCTRS-1447
> MGDCTRS-1419: feat: disable the action items if connector enters to deleted desired state

- package-lock.json
- package.json
- src/AppDemo.tsx
- src/AppE2E.tsx
- src/AppFederated.tsx
- src/CosRoutes.tsx
- src/app/components/CreateConnectorWizard/CreateConnectorWizard.tsx
- src/app/components/CreateConnectorWizard/CreateConnectorWizardContext.tsx
- src/app/machines/CreateConnectorWizard.machine.ts
- src/context/CosContext.tsx
- webpack.common.js
This change adds an interpreter to the wizard state machine that converts state transitions to user activity events.  Currently these events are directly connected to a tracking API when the app is used in federated mode, in demo and e2e test mode these activity events are logged to debug.
> MGDCTRS-1068 feat: interpret activity from state

- src/app/pages/CreateConnectorPage/StepReview.tsx
- src/utils/shared.ts
closes https://issues.redhat.com/browse/MGDCTRS-882
> MGDCTRS-882: fix:Show the boolean value on the review Page

- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryViewport.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryWrapper.tsx
- src/app/components/CreateConnectorWizard/CreateConnectorWizardContext.tsx
- src/app/components/CreateServiceAccount/CreateServiceAccount.tsx
- src/app/components/RegisterEvalNamespace/RegisterEvalNamespace.tsx
- src/app/pages/ConnectorsPage/components/ConnectorInstances/ConnectorInstances.tsx
This change tidies up the lint errors introduced with the user activity tracking changes as well as a few others.
> chore: fix lint errors

- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallery.stories.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallery.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallerySidePanel.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryToolbar.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryWrapper.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/apiExtensions.ts
- src/apis/api.ts
- src/app/pages/CreateConnectorPage/StepConnectorTypes.stories.tsx
This change adds a story to cover the initial page loading case.  Also this commit reduces the initial number of items that are fetched.
> MGDCTRS-1477 feat: add a loading story

- locales/en/cos-ui.json
- src/app/components/ErrorHandler/ErrorHandler.stories.tsx
- src/app/components/ErrorHandler/ErrorHandler.tsx
- src/app/pages/ConnectorDetailsPage/components/ConfigurationTab/ErrorHandlerStep.tsx
- src/app/pages/CreateConnectorPage/StepErrorHandling.tsx
- src/app/pages/CreateConnectorPage/StepReview.tsx
- src/utils/shared.ts
- Updated the Review page
- Added the description in the Edit flow
- Added the storybook
> MGDCTRS-1649: update the edit and review step

- locales/en/cos-ui.json
- src/apis/api.ts
- src/app/components/NamespaceCard/NamespaceCard.stories.tsx
- src/app/components/NamespaceCard/NamespaceCard.tsx
- src/app/pages/CreateConnectorPage/StepNamespace.tsx
Updated the Namespace card to show the cluster name and dropped the owner's information from the card
> Mgdctrs 1448

- src/app/components/ConnectorInfoTextList/ConnectorInfoTextList.css
- src/app/components/ConnectorInfoTextList/ConnectorInfoTextList.tsx
- src/app/pages/ConnectorDetailsPage/ConnectorDetailsPage.stories.tsx
Added more stories for the connector detail page
> storiesUpdate: chore : Added stories for connector detail page

- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallery.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryCardSkeleton.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryListView.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryViewport.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesListItem.tsx
**What this PR does / why we need it**:
> Making a list of the Connectors 
**Verification steps** 
> ![Screenshot from 2022-11-04 10-02-05](https://user-images.githubusercontent.com/72694484/199946212-8b3b3d94-36f7-4740-8138-d3fabffd541e.png)
> < PROOFOFCONCEPTS > < connectors >
**Special notes for your reviewer**:
>The icons on the far left are temporary till the ones in the mock-up are available
> chore: Connectors Listview

- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.tsx
This change updates the dependency array for a couple places where useCallback wasn't being passed all the dependencies
> chore: fix lint warnings

- public/mockServiceWorker.js
This commit adds the changes produced after updating the MSW version.
> chore: update MSW generated javascript

- locales/en/cos-ui.json
- src/app/pages/ConnectorDetailsPage/components/ConfigurationTab/CommonStep.tsx
Closes https://issues.redhat.com/browse/MGDCTRS-1895
https://user-images.githubusercontent.com/8264372/214117580-cd666d1f-1a28-415a-a114-04d2f8eff47c.mov
> MGDCTRS-1895: Save button is disabled right after Client ID is edited

- src/utils/shared.ts
https://issues.redhat.com/browse/MGDCTRS-2027
> MGDCTRS-2027:fix:Allow few special characters in search

- cypress.config.ts
- cypress/e2e/connectors-instances.cy.ts
- cypress/fixtures/connectorsEmptyPage.json
- cypress/fixtures/connectorsMany.json
- src/app/pages/ConnectorsPage/components/ConnectorInstances/ConnectorInstances.tsx
JIRA: https://issues.redhat.com/browse/MGDCTRS-1623
I've implemented Stan's proposal of showing the "No results" message when a page > 1 returns no items.
Users can then click on "clear all filters" to go back to the first page unfiltered.
> MGDCTRS-1623 fix: "No connectors instances" if there's less connectors than the current page range

- src/app/machines/CreateConnectorWizard.machine.ts
Closes https://issues.redhat.com/browse/MGDCTRS-1827
> MGDCTRS-1827: Fix the side navigation for DBZ based connectors

- cypress/fixtures/connectors/ftps_sink_0.1.json
- cypress/fixtures/connectors/ftps_source_0.1.json
- cypress/fixtures/connectors/sftp_sink_0.1.json
- cypress/fixtures/connectors/sftp_source_0.1.json
- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.stories.tsx
Demonstrating changes to the FTPS and SFTP schemas to solve the default port value validation issue.
> MGDCTRS-1923: (S)FTP: When the configuration form loads, the port field shows a validation error

- src/app/pages/CreateConnectorPage/CreateConnectorPage.css
- src/app/pages/CreateConnectorPage/CreateConnectorPage.tsx
JIRA: https://issues.redhat.com/browse/MGDCTRS-1460
> MGDCTRS-1460: Improve Next button position when creating connectors

- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.stories.tsx
#801 broke the [stories for the Connector Forms](https://6129343adbd21b003a2e0c94-emjhsbgcbu.chromatic.com/?path=/story/wizard-step-4-2-connector-form--aws-kinesis-sink&args=). Fixing 'em.
> fix: broken "Connector Form" stories
