- .github/workflows/chromatic.yaml
This should prevent the Chromatic action from running on a fork should
the fork owner decide to keep their fork up to date.
Tested locally with act and seems to work but kind of hard to test locally.  This job should still run against the main branch after merging, if it doesn't then we can revert and I can look at another way.
> chore: Check the repo owner in job, fixes #417

- src/app/pages/CreateConnectorPage/StepConnectorTypes.tsx
This ensures that the name/category query is preserved when interacting
with the pagination controls on the connector type selection page.
So, now it's possible to look at that 2nd page of AWS results for example:
> MGDCTRS-20: fix: Ensure the query is preserved

- src/app/pages/ConnectorDetailsPage/ConfigurationStep.tsx
This ensures that if the configuration doesn't contain a datashape definition
for whatever reason the configuration overview page still renders
everything else.
> MGDCTRS-734 fix: guard against undefined object

- locales/en/public.json
This fixes a typo for the i18n key that contains the modal description
for cancelling the duplicate connector flow.
> chore: fix cancel duplicate connector description key typo

- src/app/components/ConnectorDrawer/ConnectorDrawer.stories.tsx
- src/app/components/ConnectorStatus/ConnectorStatus.css
- src/app/components/ConnectorStatus/ConnectorStatus.stories.tsx
- src/app/components/ConnectorStatus/ConnectorStatus.tsx
This change removes the mapping on the UI side for all of the connector
status values and instead just titlizes the current value.  The icon
mapping is simplified as well to reflect that several of these status
values represent a transitional state.
So with all of the current backend values we have:
and
> MGDCTRS-741 fix: pass through the status values

- src/app/components/Pagination/Pagination.tsx
This adds 20 and 50 items per page options to the pagination control on
all views.
> chore: add more items per page options

- src/app/components/EmptyStateNoKafkaInstances/EmptyStateNoKafkaInstances.tsx
- src/app/components/EmptyStateNoNamespace/EmptyStateNoNamespace.stories.tsx
- src/app/components/EmptyStateNoNamespace/EmptyStateNoNamespace.tsx
This change updates the empty state titles slightly for consistency and
also fixes the storybook tree.
> MGDCTRS-699 chore: slight updates to empty states

- src/app/components/JsonSchemaConfigurator/CustomJsonSchemaBridge.tsx
- src/app/pages/ConnectorDetailsPage/ConfigurationStep.tsx
This fixes the elastic search sink connector form by correcting the way
the x-group field was interpreted, now the code properly evaluates just
the oneOf field.
So instead of:
we get:
and so on.  This also updates the detail view code to follow the same assumption.
> MGDCTRS-830: fix: correct schema assumptions

- src/app/pages/ConnectorDetailsPage/ConnectorDetailsPage.tsx
- src/app/pages/CreateConnectorPage/CreateConnectorPage.tsx
- src/app/pages/CreateConnectorPage/DuplicateConnectorPage.tsx
It turns out the BreadcrumbItem component uses a raw anchor tag which
bypasses React's router, causing a full page reload.
Fixes https://issues.redhat.com/browse/MGDCTRS-893
> MGDCTRS-893 fix: switch to the Link component

- cypress/fixtures/connectorsPolling.json
- cypress/integration/connectors.spec.ts
- src/app/components/ConnectorDrawer/ConnectorDrawer.tsx
- src/app/components/ConnectorStatus/ConnectorStatus.css
- src/app/components/ConnectorStatus/ConnectorStatus.tsx
- src/app/components/ConnectorsTable/ConnectorsTable.tsx
- src/app/pages/ConnectorDetailsPage/ConnectorDetailsPage.tsx
- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
- src/app/pages/CreateConnectorPage/StepNamespace.tsx
This change exposes the desired state field for a connector when the
connector is in a transitioning state to better inform the user what is
happening.  This commit also adds a few more rows to the
connectorsPolling fixture so it's easier to develop against the various
status possibilities.
I also tried to make some of the naming more consistent with the connector field names.
> MGDCTRS-787 feat: expose the desired state

- src/app/machines/StepConfiguratorLoader.machine.ts
- src/app/pages/ConnectorDetailsPage/ConfigurationPage.tsx
- src/app/pages/CreateConnectorPage/StepCommon.tsx
- src/app/pages/CreateConnectorPage/StepConfigurator.tsx
- Update the external UI configurator prop, from earlier `isViewMode` to `uiPath` to differenciate between edit and duplicate flow. Until now `isViewMode` was used to differentiate between create (`undefined`), edit/duplicate(`false`) and view(`true`)
- Add helper text to "Client secret " in duplicate flow.
screenshot
> MGDCTRS-892: chore: Update the configurator prop

- cypress/fixtures/connectors/aws_kinesis_sink_0.1.json
- cypress/fixtures/connectors/aws_kinesis_source_0.1.json
- cypress/fixtures/connectors/aws_s3_sink_0.1.json
- cypress/fixtures/connectors/aws_s3_source_0.1.json
- cypress/fixtures/connectors/aws_sns_sink_0.1.json
- cypress/fixtures/connectors/aws_sqs_sink_0.1.json
- cypress/fixtures/connectors/aws_sqs_source_0.1.json
- cypress/fixtures/connectors/mariadb_sink_0.1.json
- cypress/fixtures/connectors/mariadb_source_0.1.json
- cypress/fixtures/connectors/mongodb_sink_0.1.json
- cypress/fixtures/connectors/mongodb_source_0.1.json
- cypress/fixtures/connectors/mysql_sink_0.1.json
- cypress/fixtures/connectors/mysql_source_0.1.json
- cypress/fixtures/connectors/postgresql_sink_0.1.json
- cypress/fixtures/connectors/postgresql_source_0.1.json
- cypress/fixtures/connectors/sqlserver_sink_0.1.json
- cypress/fixtures/connectors/sqlserver_source_0.1.json
- src/app/components/JsonSchemaConfigurator/CustomJsonSchemaBridge.tsx
- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.stories.tsx
This change addresses how uniforms can represent what is valid data in
an inconsistent way.  For enums if the underlying model object is unset,
uniforms will still show the first enum value, leading the user to
believe that the field is configured.  This change works around this by
inserting empty enum values as needed into the schema definition so it's
not necessary for the schema to have to deal with a UI concern.
With this change the connector creation wizard will require the user to select the appropriate region:
I also opted to manually update the fixtures from the current catalog in this commit as well, maybe this is something that could be automated in the future.
> MGDCTRS-1044 fix: ensure unset enums show as unset

- cypress.json
- src/apis/api.ts
- src/app/components/ConnectorsToolbar/ConnectorsToolbar.tsx
- src/app/components/CreateConnectorWizard/CreateConnectorWizardContext.tsx
- src/app/components/Pagination/Pagination.tsx
- src/app/machines/ConnectorsPage.machine.ts
- src/app/machines/PaginatedResponse.machine.ts
- src/app/machines/StepConnectorTypes.machine.ts
- src/app/machines/StepKafkas.machine.ts
- src/app/machines/StepNamespace.machine.ts
- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
- src/app/pages/ConnectorsPage/ConnectorsPageContext.tsx
- src/app/pages/CreateConnectorPage/StepConnectorTypes.tsx
- src/app/pages/CreateConnectorPage/StepKafkas.tsx
- src/app/pages/CreateConnectorPage/StepNamespace.tsx
- test/PaginatedResponseMachine.test.tsx
This change updates the pagination utility classes to add support for
orderBy and aligns the filtering support to better match the API.  This
change also updates the pagination usage a little bit across the
toolbars in the application.  Finally this change also brings back the
search filter on the connectors instance list.  Further work is needed
to add sorting controls as well as additional filter categories for the
connectors instance list search.
> MGDCTRS-772 feat: server-side filtering/ordering

- src/app/components/Pagination/Pagination.css
- src/app/components/Pagination/Pagination.tsx
This change adds some padding to the bottom of the lower pagination
control to ensure it occupies enough page space so that it isn't
overlapped by the resource icon.  This change also corrects a visual bug
on the connector type selection page.
and also (the drop shadow on the bottom card was being hidden):
> MGDCTRS-967 fix: add padding to the page bottom

- .env
- src/app/pages/ConnectorDetailsPage/ConfigurationTab.tsx
- src/app/pages/ConnectorDetailsPage/ConfigurationTab/CommonStep.tsx
This PR updates SA fields in the edit connector flow. Added helper text to the Client Secret field. 
When you edit SA Client Id It displays the Client Secret field with 5 pre-field bullet points. Once you update the secret field with a new value you can see the EyeIcon which shows/hide entered value. It also validates the empty values
> MGDCTRS-1149:chore: update SA fields in edit connector flow

- cypress/integration/connectors.spec.ts
- locales/en/public.json
- src/apis/api.ts
- src/app/components/ConnectorDrawer/ConnectorDrawer.tsx
- src/app/components/ConnectorInfoTextList/ConnectorInfoTextList.css
- src/app/components/ConnectorInfoTextList/ConnectorInfoTextList.tsx
- src/app/pages/ConnectorDetailsPage/OverviewTab.tsx
- src/bootstrap.tsx
Closes https://issues.redhat.com/browse/MGDCTRS-1067
- Show the KI name in place of the id
- Clickable KI name to open KI in use in the new tab
- MSG for expired KI
- Show loader when KI and Namespace call is being made
> MGDCTRS-1067: fix: Improve the KI shown in overview and drawer

- locales/en/public.json
- src/CosRoutes.tsx
- src/app/components/ConnectorDrawer/ConnectorDrawer.tsx
- src/app/components/ConnectorInfoTextList/ConnectorInfoTextList.tsx
- src/app/pages/ConnectorDetailsPage/ConnectorDetailsPage.tsx
- src/app/pages/ConnectorDetailsPage/OverviewTab.tsx
Closes https://issues.redhat.com/browse/MGDCTRS-1189
- Add the option to duplicate a connector from **drawer** and **overview page** if KI no longer exists.
screenshot
> MGDCTRS-1189: feat:Add option to duplicate a connector for expired KI

- src/AppDemo.tsx
- src/app/components/AppLayout/AppLayout.tsx
This change adds a dropdown menu to select a backend instance, either
staging, development or local.  It stores the selection in local storage
so the last environment used will be selected.  This change also shows
the currently connected environment in the page header.
This beats forgetting to uncomment the right URL in the .env file when you need to work against a particular environment.
> feat: add a backend environment selector

- cypress/e2e/connectors-instances.cy.ts
- cypress/fixtures/connectorsPolling.json
- src/app/components/DialogDeleteConnector/DialogDeleteConnector.tsx
- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
This change restores the delete confirmation dialog prompt on the
connector instances table and adds an integration test to ensure it
continues to behave as intended.
> MGDCTRS-1421 fix: show the delete confirmation

- cypress/e2e/connector-overview.cy.ts
- src/apis/api.ts
- src/app/pages/ConnectorDetailsPage/ConfigurationTab.tsx
- src/app/pages/ConnectorDetailsPage/ConfigurationTab/ErrorHandlerStep.tsx
- src/utils/shared.ts
- test/shared.test.tsx
This changes adjusts the overview to send the correct patch request when the user changes the error handling strategy.  This change also adds tests and tries to add a little bit more type info given that error handling doesn't yet seem to be exposed by the API.
Oh, also I changed a couple console.log statements in the API just to make them more consistent.
> MGDCTRS-1420 fix: send the correct patch

- src/AppDemo.tsx
- src/AppE2E.tsx
- src/AppFederated.tsx
- src/CosRoutes.tsx
- src/app/components/ConnectorDrawer/ConnectorDrawer.tsx
- src/app/components/CreateConnectorWizard/CreateConnectorWizardContext.tsx
- src/app/components/CreateServiceAccount/CreateServiceAccount.stories.tsx
- src/app/components/CreateServiceAccount/CreateServiceAccount.tsx
- src/app/components/RegisterEvalNamespace/RegisterEvalNamespace.tsx
- src/app/pages/ConnectorDetailsPage/ConfigurationTab.tsx
- src/app/pages/ConnectorDetailsPage/ConnectorDetailsPage.tsx
- src/app/pages/ConnectorDetailsPage/OverviewTab.tsx
- src/app/pages/ConnectorsPage/ConnectorsPage.tsx
- src/app/pages/CreateConnectorPage/CreateConnectorPage.tsx
- src/app/pages/CreateConnectorPage/DuplicateConnectorPage.tsx
- src/hooks/useAnalytics.tsx
- src/hooks/useCos.tsx
- tsconfig.json
This change updates how analytics are made available to the app via using a custom hook that's configurable via a context.  This change also updates the directory structure and filenames for clarity, i.e. "context" to "hooks" for hooks that cover app-wide concerns such as analytics or basic app configuration like the existing useCos hook.
I totally should have done this the first time around :-)
> MGDCTRS-1068 fix: add an analytics hook

- src/app/components/ConnectorTypeCard/ConnectorTypeCard.stories.tsx
- src/app/components/CreateConnectorWizard/CreateConnectorWizardContext.tsx
- src/app/pages/CreateConnectorPage/StepConnectorTypes.stories.tsx
- src/constants/constants.tsx
This change adds a story that loads the Select Connector Type step from the wizard and mocks the API.  There's also a couple of small cleanup items, an update to the error string when the trying to use the wizard without it's provider and removal of an unused constant.
> MGDCTRS-1477 chore: select connector type story

- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallery.stories.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryCache.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryCard.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryViewport.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryWrapper.tsx
This change adds a 2nd story that shows a card layout using Masonry from react-virtualized.
In a list layout:
And in the card layout:
this also reduces the number of items to a more sensible number :smile:
> MGDCTRS-1477 feat: add a card layout variant

- cypress/fixtures/connectors/aws_kinesis_source_0.1.json
- cypress/fixtures/connectors/aws_s3_sink_0.1.json
- cypress/fixtures/connectors/debezium-postgres-1.9.4.Alpha1.json
- src/app/components/JsonSchemaConfigurator/CustomJsonSchemaBridge.tsx
- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.tsx
- src/app/components/JsonSchemaConfigurator/TypeaheadField.tsx
- src/app/components/ViewJSONFormat/ViewJSONFormat.stories.tsx
- src/app/pages/ConnectorDetailsPage/components/ConfigurationTab/ConfigurationStep.tsx
- src/app/pages/CreateConnectorPage/StepReview.stories.tsx
- src/utils/createValidator.ts
- src/utils/shared.ts
This change adds a method to start applying some general organization to the schema driven forms.  The kafka topic should be moved to the start of the form, and for AWS based connectors the access key/secret fields are next, followed by the region.  The other change this commit brings in is a new custom control for schema based forms to improve the AWS region selector so that it behaves more like a typeahead control and less like a select control.
> MGDCTRS-1153 feat: dynamic form improvements

- src/app/pages/ConnectorsPage/ConnectorsPage.stories.tsx
- src/app/pages/ConnectorsPage/components/ConnectorActions/ConnectorActions.tsx
- src/app/pages/ConnectorsPage/components/ConnectorInstancesTable/ConnectorInstancesTable.css
- src/app/pages/ConnectorsPage/components/ConnectorInstancesTable/ConnectorInstancesTable.tsx
This change adds back in the workaround to attach an instance's actions to the document body and adds some margin underneath the table so that the page is hopefully tall enough to accommodate the action menu for even the last instance.
> MGDCTRS-1438 fix: add some margin under the table

- src/app/machines/PaginatedResponse.machine.ts
It fixes the issue when unable to select a newly added Kafka Instance or Namespace when polling is enabled.
> MGDCTRS-1524:fix:Selecting KI immediately after creating it won't work

- locales/en/cos-ui.json
- src/app/components/JsonSchemaConfigurator/CheckboxWithDescriptionField.tsx
- src/app/components/JsonSchemaConfigurator/CustomJsonSchemaBridge.tsx
- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.tsx
- src/app/components/NamespaceCard/NamespaceCard.tsx
> MGDCTRS-1388: feat: Add custom component for boolean field

- package-lock.json
- package.json
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallery.css
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallery.stories.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallery.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryCache.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryCard.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryCardSkeleton.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallerySidePanel.css
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGallerySidePanel.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryViewport.css
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryViewport.tsx
- src/ProofOfConcepts/ConnectorTypesGallery/ConnectorTypesGalleryWrapper.tsx
This change adds some calculation to set the viewport height for the connector type list so that it adjusts with the window size.  It also does the same for the category panel.  This change also removes the code supporting the card view and Masonry in favor of one approach.
> MGDCTRS-1477 feat: dynamic list viewport height

- .storybook/preview.js
- cypress/e2e/connector-create.cy.ts
- locales/en/cos-ui.json
- src/app/components/CreateConnectorWizard/CreateConnectorWizardContext.tsx
- src/app/components/JsonSchemaConfigurator/JsonSchemaConfigurator.stories.tsx
- src/app/components/ViewJSONFormat/ViewJSONFormat.stories.tsx
- src/app/machines/CreateConnectorWizard.machine.ts
- src/app/machines/StepCoreConfiguration.machine.ts
- src/app/pages/CreateConnectorPage/StepCoreConfiguration.css
- src/app/pages/CreateConnectorPage/StepCoreConfiguration.stories.tsx
- src/app/pages/CreateConnectorPage/StepCoreConfiguration.tsx
- src/app/pages/CreateConnectorPage/StepReview.stories.tsx
This commit adds some text and a link to the core configuration step to the user guide that covers service account creation and configuration for Kafka.  This change also adds reworks the core configuration step and adds some stories to storybook so it's easier to develop this step outside of the application.
Here's the storybook additions:
And when the user checks the checkbox:
Finally the review step change:
> MGDCTRS-1850 chore: add a link to the SA guide

- src/apis/api.ts
This change fixes a typo when building the SQL query for filtering labels by pricing_tier.
> MGDCTRS-1883 chore: fix typo

- src/app/components/SomethingWentWrongInline/SomethingWentWrongInline.tsx
- src/app/components/SomethingWentWrongInline/SomethingWentWrongInlineNoSubscription.tsx
This change removes the monospace font from the email address used in the error handler alert message.
> MGDCTRS-1773 fix: remove code formatting

- src/app/pages/CreateConnectorPage/StepReview.tsx
This change updates the review step to show the correct value for the field on the UI labeled "type".  This commit also removes a couple unnecessary type annotations.
> MGDCTRS-1826 fix: show the correct value

- locales/en/cos-ui.json
- src/app/components/ConnectorSelectionList/ConnectorSelectionListFilterPanel.tsx
This change adds some missing text into the subscription tier popover, replacing some TODOs.
> MGDCTRS-1875 fix: update missing copy text

- src/app/components/ConnectorSelectionList/ConnectorSelectionListFilterPanel.tsx
This change removes the label counts from the filter panel; there's debate on the behavior of the counts and if these counts provide value.
> MGDCTRS-1904 fix: hide label counts

- src/app/components/ConnectorSelectionList/ConnectorSelectionListItem.tsx
- src/app/components/ConnectorSelectionList/ConnectorSelectionListToolbar.tsx
This change removes the sort control from the connector type selector toolbar to save some screen real estate.  This commit also updates icon used when the filter control collapses in narrower viewports.  Finally, this change also includes a small tweak to the order in the labels for featured items to be consistent.
> MGDCTRS-1912 fix: remove sort control

- src/app/components/ConnectorSelectionList/ConnectorSelectionList.stories.tsx
- src/app/components/ConnectorSelectionList/ConnectorSelectionList.tsx
- src/app/components/ConnectorSelectionList/ConnectorSelectionListCache.tsx
- src/app/components/ConnectorSelectionList/ConnectorSelectionListCacheStorage.tsx
- src/app/pages/CreateConnectorPage/CreateConnectorPage.tsx
This change separates the cache used to store connector types by the connector selection list into two separate components, one component to act as a simple storage to cache API responses, and a second component that takes care of managing that cache based on application state, so that the storage of API responses can be lifted to a point where it won't be discarded due to a rerender, which occurs when the user selects an item from the list.
Now you can scroll, click on a list item and then still scroll and nothing weird happens like it was behaving before :smile:
> MGDCTRS-1922 fix: decouple cache storage

- src/app/components/DialogDeleteConnector/DialogDeleteConnector.tsx
This commit enables the user to type the connector name and press enter to confirm deleting a connector provided the connector name matches.
> MGDCTRS-1456 fix: handle enter key in delete modal

- package-lock.json
- package.json
- src/app/components/ConnectorSelectionList/ConnectorSelectionListToolbar.tsx
This commit bumps the patternfly react-core version and applies a small change required by this update.
This will unstick #724
> chore: bump @patternfly/react-core

- src/app/components/ConnectorSelectionList/ConnectorSelectionListFilterPanel.tsx
- src/app/components/ConnectorSelectionList/ConnectorSelectionListItem.tsx
This change temporarily hides the filter and pricing tier badge from the UI until it's needed.
> MGDCTRS-2139 chore: hide pricing tier elements

- locales/en/cos-ui.json
This change removes an incorrect statement in the description text for the ignore error handler method.
> MGDCTRS-2235 chore: update ignore description

- src/app/pages/CreateConnectorPage/DuplicateConnectorPage.tsx
Same as #782 but for the connectors duplication page.
The wizard actions footer will always be visible at the bottom of the viewport.
> fix: Improve Next button position when duplicating connectors

- cypress/e2e/connector-create.cy.ts
- cypress/e2e/connector-overview.cy.ts
- cypress/e2e/connectors-instances.cy.ts
- src/CosRoutes.tsx
- src/app/components/EmptyStateGettingStarted/EmptyStateGettingStarted.tsx
- src/app/pages/ConnectorsPage/components/ConnectorInstancesTable/ConnectorInstancesTable.tsx
This change disables or removes buttons from the entry page as well as adds redirects to the create/duplicate app paths so that connector instances cannot be created via the UI.
> MGDCTRS-2303 chore: disable connector creation
